core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('usuarios/', include('usuarios.urls')),
    path('mentorados/', include('mentorados.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mentorados/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.mentorados, name='mentorados'),
    path('reunioes/', views.reunioes, name='reunioes'),
    path('auth/', views.auth, name="auth_mentorado"),
    path('escolher_dia/', views.escolher_dia, name='escolher_dia'),
    path('agendar_reuniao/', views.agendar_reuniao, name='agendar_reuniao'),
    path('tarefa/<int:id>', views.tarefa, name='tarefa'),
    path('upload/<int:id>', views.upload, name='upload'),
    path('tarefa_mentorado/', views.tarefa_mentorado, name='tarefa_mentorado'),
    path('tarefa_alterar/<int:id>', views.tarefa_alterar, name="tarefa_alterar")
]

mentorados/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import timedelta
import secrets

class Navigators(models.Model):
    nome = models.CharField(max_length=255)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.nome
    
class Mentorados(models.Model):
    estagio_choices = (
        ('E1', '10-100k'),
        ('E2', '100-1KK')
    )
    nome = models.CharField(max_length=255)
    foto = models.ImageField(upload_to='fotos', null=True, blank=True)
    estagio = models.CharField(max_length=2, choices=estagio_choices)
    navigator = models.ForeignKey(Navigators, null=True, blank=True, on_delete=models.SET_NULL)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    criado_em = models.DateField(auto_now_add=True)
    token = models.CharField(max_length=16)

    def save(self, *args, **kwargs):
        if not self.token:
            self.token = self.gerar_token_unico()
        super().save(args, **kwargs)

    def gerar_token_unico(self):
        while True:
            token = secrets.token_urlsafe(8)
            if not Mentorados.objects.filter(token=token).exists():
                return token
 
    def __str__(self):
        return self.nome

class DisponibilidadeHorarios(models.Model):
    data_inicial = models.DateTimeField(null=True, blank=True)
    mentor = models.ForeignKey(User, on_delete=models.CASCADE)
    agendado = models.BooleanField(default=False)

    def data_final(self):
        return self.data_inicial + timedelta(minutes=50)

class Reuniao(models.Model):
    tag_choices = (
        ('G', 'Gestão'),
        ('M', 'Marketing'),
        ('RH', 'Gestão de pessoas'),
        ('I', 'Impostos')
    )

    data = models.ForeignKey(DisponibilidadeHorarios, on_delete=models.CASCADE)
    mentorado = models.ForeignKey(Mentorados, on_delete=models.CASCADE)
    tag = models.CharField(max_length=2, choices=tag_choices)
    descricao = models.TextField()


class Tarefa(models.Model):
    mentorado = models.ForeignKey(Mentorados, on_delete=models.DO_NOTHING)
    tarefa = models.CharField(max_length=255)
    realizada = models.BooleanField(default=False)


class Upload(models.Model):
    mentorado = models.ForeignKey(Mentorados, on_delete=models.DO_NOTHING)
    video = models.FileField(upload_to='video')

mentorados/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, Http404
from .models import Mentorados, Navigators, DisponibilidadeHorarios, Reuniao, Tarefa, Upload
from django.contrib import messages
from django.contrib.messages import constants
from datetime import datetime, timedelta
from .auth import valida_token
from django.contrib.auth.decorators import login_required

@login_required
def mentorados(request):
    if request.method == 'GET':
        navigators = Navigators.objects.filter(user=request.user)
        mentorados = Mentorados.objects.filter(user=request.user)


        estagios_flat = []
        for i in Mentorados.estagio_choices:
            estagios_flat.append(i[1])


        qtd_estagios=[]
        for i, j in Mentorados.estagio_choices:
            x = Mentorados.objects.filter(estagio=i).filter(user=request.user).count()
            qtd_estagios.append(x)

        print(estagios_flat)
        print(qtd_estagios)

        return render(request, 'mentorados.html', {'estagios': Mentorados.estagio_choices, 'navigators': navigators, 'mentorados': mentorados, 'estagios_flat': estagios_flat, 'qtd_estagios': qtd_estagios})
    else:
        nome = request.POST.get('nome')
        foto = request.FILES.get('foto')
        estagio = request.POST.get("estagio")
        navigator = request.POST.get('navigator')

        mentorado = Mentorados(
            nome=nome,
            foto=foto,
            estagio=estagio,
            navigator_id=navigator,
            user=request.user
        )

        mentorado.save()

        messages.add_message(request, constants.SUCCESS, 'Mentorado cadastrado com sucesso.')
        return redirect('mentorados')

def reunioes(request):
    if request.method == 'GET':
        reunioes = Reuniao.objects.filter(data__mentor=request.user)
        return render(request, 'reunioes.html', {'reunioes':reunioes})
    else:
        data = request.POST.get('data')

        data = datetime.strptime(data, '%Y-%m-%dT%H:%M')

        disponibilidades = DisponibilidadeHorarios.objects.filter(
            data_inicial__gte=(data - timedelta(minutes=50)),
            data_inicial__lte=(data + timedelta(minutes=50))
        )

        if disponibilidades.exists():
            messages.add_message(request, constants.ERROR, 'Você já possui uma reunião em aberto.')
            return redirect('reunioes')

        disponibilidades = DisponibilidadeHorarios(
            data_inicial=data,
            mentor=request.user

        )
        disponibilidades.save()

        messages.add_message(request, constants.SUCCESS, 'Horário disponibilizado com sucesso.')
        return redirect('reunioes')

def auth(request):
    if request.method == 'GET':
        return render(request, 'auth_mentorado.html')
    else:
        token = request.POST.get('token')

        if not Mentorados.objects.filter(token=token).exists():
            messages.add_message(request, constants.ERROR, 'Token inválido')
            return redirect('auth_mentorado')
        
        response = redirect('escolher_dia')
        response.set_cookie('auth_token', token, max_age=3600)
        return response

def escolher_dia(request):
    if not valida_token(request.COOKIES.get('auth_token')):
        return redirect('auth_mentorado')

    if request.method == 'GET':
        mentorado = valida_token(request.COOKIES.get('auth_token'))

        disponibilidades = DisponibilidadeHorarios.objects.filter(
            data_inicial__gte=datetime.now(),
            agendado=False,
            mentor=mentorado.user
        ).values_list('data_inicial', flat=True)

        datas = []
        for i in disponibilidades:
           datas.append(i.date().strftime('%d-%m-%Y'))

        return render(request, 'escolher_dia.html', {'horarios': list(set(datas))})

def agendar_reuniao(request):
    if not valida_token(request.COOKIES.get('auth_token')):
        return redirect('auth_mentorado')
    mentorado = valida_token(request.COOKIES.get('auth_token'))
    if request.method == 'GET':
        data = request.GET.get('data')
        data = datetime.strptime(data, '%d-%m-%Y')
        
        horarios = DisponibilidadeHorarios.objects.filter(
            data_inicial__gte=data,
            data_inicial__lt=data + timedelta(days=1),
            agendado=False,
            mentor=mentorado.user

        )
        return render(request, 'agendar_reuniao.html', {'horarios': horarios, 'tags': Reuniao.tag_choices})
    else:
        horario_id = request.POST.get('horario')
        tag = request.POST.get('tag')
        descricao = request.POST.get('descricao')

        reuniao = Reuniao(
            data_id=horario_id,
            mentorado=mentorado,
            tag=tag,
            descricao=descricao
        )
        reuniao.save()

        horario = DisponibilidadeHorarios.objects.get(id=horario_id)
        horario.agendado = True
        horario.save()

        messages.add_message(request, constants.SUCCESS, 'Reunião agendada com sucesso')
        return redirect('escolher_dia')

def tarefa(request, id):
    mentorado = Mentorados.objects.get(id=id)
    if mentorado.user != request.user:
        raise Http404()

    if request.method == 'GET':
        tarefas = Tarefa.objects.filter(mentorado=mentorado)
        videos = Upload.objects.filter(mentorado=mentorado)
        return render(request, 'tarefa.html', {'mentorado': mentorado, 'tarefas': tarefas, 'videos': videos})
    else:
        tarefa = request.POST.get('tarefa')

        t = Tarefa(
            mentorado=mentorado,
            tarefa=tarefa
        )
        t.save() 
    return redirect(f'/mentorados/tarefa/{id}')

def upload(request, id):
    mentorado = Mentorados.objects.get(id=id)
    if mentorado.user != request.user:
        raise Http404()
    
    video = request.FILES.get('video')
    upload = Upload(
        mentorado=mentorado,
        video=video
    )
    upload.save()
    return redirect(f'/mentorados/tarefa/{id}')

def tarefa_mentorado(request):
    mentorado = valida_token(request.COOKIES.get('auth_token'))
    if not mentorado:
        return redirect('auth_mentorado')

    if request.method == 'GET':
        videos = Upload.objects.filter(mentorado=mentorado)
        tarefas = Tarefa.objects.filter(mentorado=mentorado)
        return render(request, 'tarefa_mentorado.html', {'mentorado': mentorado, 'videos': videos, 'tarefas': tarefas})

from django.views.decorators.csrf import csrf_exempt

@csrf_exempt
def tarefa_alterar(request, id):
    tarefa = Tarefa.objects.get(id=id)

    tarefa.realizada = not tarefa.realizada
    tarefa.save()
    return HttpResponse('teste')

mentorados/templates/auth_mentorado.html
{% extends "base.html" %}

{% block 'body' %}
    <div class="bg-gray-900 flex items-center justify-center h-screen">
        <div class="bg-gray-800 p-8 rounded-lg shadow-lg text-center w-96">
            <form action="{% url 'auth_mentorado' %}" method="POST"> {% csrf_token %}
                
                <h2 class="text-2xl font-bold text-gray-200 mb-4">Acessar conteúdo</h2>
                {% if messages %}
                    {% for message in messages %}
                        <div class="rounded-md {{message.tags}} mt-4">
                            <div class="flex">
                                <div class="ml-3 py-4">
                                    {{message}}

                                </div>

                            </div>
                        </div>
                    {% endfor %}
                {% endif %}
                <label class="text-gray-400 block text-left mb-1">Token de acesso</label>
                <input type="text" name="token" class="w-full p-3 rounded-md bg-gray-300 text-gray-800 focus:outline-none focus:ring-2 focus:ring-blue-500" placeholder="Digite seu token">

                <button class="w-full mt-4 bg-indigo-600 text-white font-semibold p-3 rounded-md hover:bg-indigo-700 transition cursor-pointer">Acessar</button>
            </form>
        </div>
    </div>
{% endblock 'body' %}

mentorados/templates/mentorados.html
{% extends "base.html" %}
{% load static %}
{% block 'body' %}
<header class="bg-slate-900">
    <nav class="flex items-center justify-between p-4 lg:px-8" aria-label="Global">
      <div class="flex lg:flex-1">
        <a href="#" class="-m-1.5 p-1.5">
          <span class="sr-only">Your Company</span>
          <img class="h-8 w-auto" src="{% static 'logo.png' %}" alt="">
        </a>
      </div>
      <div class="flex lg:hidden">
        <button type="button" class="-m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-gray-700">
          <span class="sr-only">Open main menu</span>
          <svg class="size-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true" data-slot="icon">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
          </svg>
        </button>
      </div>
      <div class="hidden lg:flex lg:gap-x-12">
        <a href="{% url 'mentorados' %}" class="text-sm/6 font-semibold text-gray-100">Mentorados</a>
        <a href="{% url 'reunioes' %}" class="text-sm/6 font-semibold text-gray-100">Reuniões</a>
      </div>
      <div class="hidden lg:flex lg:flex-1 lg:justify-end">
        
      </div>
    </nav>
    
    </div>
  </header>
  
 
  <div class="bg-[#040e1b] min-h-screen">
    <div class="max-w-7xl mx-auto py-12">
        <div class="grid grid-cols-2 gap-4">
            <div>
              <form action="{% url 'mentorados' %}" method="POST" enctype='multipart/form-data'>{% csrf_token %}
                <h2 class="mt-4 text-2xl/9 font-bold tracking-tight text-gray-100">Cadastre seus mentorados</h2> 
                {% if messages %}
                    {% for message in messages %}
                        <div class="rounded-md {{message.tags}} mt-4">
                            <div class="flex">
                                <div class="ml-3 py-4">
                                    {{message}}

                                </div>

                            </div>
                        </div>
                    {% endfor %}
                {% endif %}
                <div>
                    <label for="email" class="block text-sm/6 font-medium text-gray-200">Nome</label>
                    <div class="mt-2">
                        <input type="text" name="nome" required class="block w-full rounded-md bg-white/5 px-3 py-1.5 text-base text-white outline outline-1 -outline-offset-1 outline-white/10 placeholder:text-gray-500 focus:outline focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-500 sm:text-sm/6">
                      </div>
                </div>
                <div class="grid grid-cols-2 gap-4 mt-4">
                    <div>
                        <label class="block text-sm/6 font-medium text-gray-200">Foto</label>
                        <div class="mt-2">
                            <input type="file" name="foto" id="foto" autocomplete="foto" required class="block w-full rounded-md bg-white/5 px-3 py-1.5 text-base text-white outline outline-1 -outline-offset-1 outline-white/10 placeholder:text-gray-500 focus:outline focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-500 sm:text-sm/6">
                        </div>
                    </div>
                    <div>
                        <label class="block text-sm/6 font-medium text-gray-200">Estágio</label>
                    
                        <div class="mt-2">
                            <select name="estagio" id="" class="block w-full rounded-md bg-white/5 px-3 py-2 text-base text-white outline outline-1 -outline-offset-1 outline-white/10 placeholder:text-gray-500 focus:outline focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-500 sm:text-sm/6">
                                
                                {% for estagio in estagios  %}
                                <option class="text-slate-900" value="{{estagio.0}}">{{estagio.1}}</option>
                                {% endfor %}

                            </select>
                           
                        </div>
                    </div>

                </div>

                <div class="mt-4">
                        <label class="block text-sm/6 font-medium text-gray-200">Navigator</label>
                        <div class="mt-2">
                            <select name="navigator" id="" class="block w-full rounded-md bg-white/5 px-3 py-2 text-base text-white outline outline-1 -outline-offset-1 outline-white/10 placeholder:text-gray-500 focus:outline focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-500 sm:text-sm/6">

                                {% for navigator in navigators  %}
                                <option value="{{navigator.id}}">{{navigator.nome}}</option>  
                                {% endfor %}

                                <option value="">Caio</option>      
                              
                            </select>
                           
                        </div>
                        <br>
                        <button type="submit" class="flex w-full justify-center cursor-pointer rounded-md bg-indigo-600 px-3 py-1.5 text-sm/6 font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Cadastrar</button>
                </div>
              </form>
            </div>

            <div class="flex justify-center items-center w-1/2 mx-auto">
                <canvas id="myChart" class="w-24 h-24"></canvas>
            </div>


        </div>
        <div class="mt-6">
            <hr class="border-gray-600">
            <br>    
            <h2 class="text-base/7 font-semibold text-white ">Seus mentorados</h2>
            <table class="mt-6 w-full whitespace-nowrap text-left">
              <colgroup>
                <col class="w-full sm:w-4/12">
                <col class="lg:w-4/12">
                <col class="lg:w-2/12">
                <col class="lg:w-1/12">
                <col class="lg:w-1/12">
              </colgroup>
              <thead class="border-b border-white/10 text-sm/6 text-white">
                <tr>
                  <th scope="col" class="py-2 pl-4 pr-8 font-semibold sm:pl-6 lg:pl-8">Usuário</th>
                  <th scope="col" class="hidden py-2 pl-0 pr-8 font-semibold sm:table-cell">Estágio</th>
                  <th scope="col" class="py-2 pl-0 pr-4 text-right font-semibold sm:pr-8 sm:text-left lg:pr-20">Status</th>
                  <th scope="col" class="hidden py-2 pl-0 pr-8 font-semibold md:table-cell lg:pr-20">Data entrada</th>
                  <th scope="col" class="hidden py-2 pl-0 pr-8 font-semibold md:table-cell lg:pr-20">Navigator</th>
                </tr>
              </thead>
              <tbody class="divide-y divide-white/5">
                
                {% for mentorado in mentorados %}
                    <tr>
                      <td class="py-4 pl-4 pr-8 sm:pl-6 lg:pl-8">
                        <div class="flex items-center gap-x-4">
                          <img src="{{mentorado.foto.url}}" alt="" class="size-8 rounded-full bg-gray-800">
                          <div class="truncate text-sm/6 font-medium text-white"><a href="{% url 'tarefa' mentorado.id %}">{{mentorado.nome}}</a></div>
                        </div>
                      </td>
                      <td class="hidden py-4 pl-0 pr-4 sm:table-cell sm:pr-8">
                        <div class="flex gap-x-3">
                          <div class="rounded-md bg-gray-700/40 px-2 py-1 text-xs font-medium text-gray-400 ring-1 ring-inset ring-white/10">{{mentorado.get_estagio_display}}</div>
                        </div>
                      </td>
                      <td class="py-4 pl-0 pr-4 text-sm/6 sm:pr-8 lg:pr-20">
                        <div class="flex items-center justify-end gap-x-2 sm:justify-start">
                          <div class="flex-none rounded-full bg-green-400/10 p-1 text-green-400">
                            <div class="size-1.5 rounded-full bg-current"></div>
                          </div>
                          <div class="hidden text-white sm:block">Ativo</div>
                        </div>
                      </td>
                      <td class="hidden py-4 pl-0 pr-8 text-sm/6 text-gray-400 md:table-cell lg:pr-20">2{{mentorado.criado_em}}</td>
                      <td class="hidden py-4 pl-0 pr-8 text-sm/6 text-gray-400 md:table-cell lg:pr-20">
                      
                          {{mentorado.navigator.nome}}
                      </td>
                    </tr>
                {% endfor %}

              </tbody>
            </table>
          </div>

    </div>
     
  </div>

  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<script>
  const ctx = document.getElementById('myChart');

  new Chart(ctx, {
    type: 'pie',
    data: {
      labels: {{estagios_flat|safe}},
      datasets: [{
        label: '',
        data: {{qtd_estagios|safe}},
        borderWidth: 1
      }]
    },
    
  });
</script>


{% endblock 'body' %}

mentorados/templates/tarefa.html
{% extends "base.html" %}
{% load static %}
{% block 'body' %}
<header class="bg-slate-900">
    <nav class="flex items-center justify-between p-4 lg:px-8" aria-label="Global">
      <div class="flex lg:flex-1">
        <a href="#" class="-m-1.5 p-1.5">
          <span class="sr-only">Your Company</span>
          <img class="h-8 w-auto" src="{% static 'logo.png' %}" alt="">
        </a>
      </div>
      <div class="flex lg:hidden">
        <button type="button" class="-m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-gray-700">
          <span class="sr-only">Open main menu</span>
          <svg class="size-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true" data-slot="icon">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
          </svg>
        </button>
      </div>
      <div class="hidden lg:flex lg:gap-x-12">
        <a href="{% url 'mentorados' %}" class="text-sm/6 font-semibold text-gray-100">Mentorados</a>
        <a href="{% url 'reunioes' %}" class="text-sm/6 font-semibold text-gray-100">Reuniões</a>
      </div>
      <div class="hidden lg:flex lg:flex-1 lg:justify-end">
        
      </div>
    </nav>
    
  </header>
  
 
 
  
  <main>
    <header class="relative isolate pt-16 bg-[#0b1526] border-b-1 border-slate-500">
      <div class="absolute inset-0 -z-10 overflow-hidden" aria-hidden="true">
        <div class="absolute left-16 top-full -mt-16 transform-gpu opacity-50 blur-3xl xl:left-1/2 xl:-ml-80">
          <div class="aspect-[1154/678] w-[72.125rem] bg-gradient-to-br from-[#FF80B5] to-[#9089FC]" style="clip-path: polygon(100% 38.5%, 82.6% 100%, 60.2% 37.7%, 52.4% 32.1%, 47.5% 41.8%, 45.2% 65.6%, 27.5% 23.4%, 0.1% 35.3%, 17.9% 0%, 27.7% 23.4%, 76.2% 2.5%, 74.2% 56%, 100% 38.5%)"></div>
        </div>
        <div class="absolute inset-x-0 bottom-0 h-px bg-gray-900/5"></div>
      </div>
      <div>
      <div class="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8 ">
        <div class="mx-auto flex max-w-2xl items-center justify-between gap-x-8 lg:mx-0 lg:max-w-none">
          <div class="flex items-center gap-x-6">
            <img src="{{mentorado.foto.url}}" alt="" class="size-16 flex-none rounded-full ring-1 ring-gray-900/10">
            <h1>
              <div class="mt-1 text-base font-semibold text-gray-200">{{mentorado}}</div>
              <div class="text-sm/6 text-gray-500">{{mentorado.get_estagio_display}}</div>
            </h1>
          </div>
        
          </div>
        </div>
      </div>
    </div>
    </header>
    
    <div class="bg-[#05101d] min-h-screen">
        <div class="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8">
        <div class="mx-auto grid max-w-2xl grid-cols-1 grid-rows-1 items-start gap-x-8 gap-y-8 lg:mx-0 lg:max-w-none lg:grid-cols-3">
            <!-- Invoice summary -->
            <div class="lg:col-start-3 lg:row-end-1 ">
            <h2 class="sr-only">Summary</h2>
            <div class="rounded-lg shadow-sm ring-1 ring-white/20 bg-[#0b1526]">
                <dl class="flex flex-wrap">
                <div class="flex-auto px-6 pt-6">
                    <p class="text-sm/6 font-semibold text-indigo-200">Reuniões</p>
                    <div class="grid grid-cols-4 gap-5">
                        <div class="col-span-3">
                          <form action="{% url 'upload' mentorado.id %}" method="POST" enctype='multipart/form-data'>{% csrf_token %}
                            <input type="file" name="video" required class="block w-full rounded-md bg-white/5 px-3 py-1.5 text-base text-white outline outline-1 -outline-offset-1 outline-white/10 placeholder:text-gray-500 focus:outline focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-500 sm:text-sm/6">
                        </div>
                        <div>
                            <button type="submit" class="flex w-full justify-center cursor-pointer rounded-md bg-indigo-600 px-3 py-1.5 text-sm/6 font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Entrar</button>
                          </form>
                        </div>

                    </div>
                    
                </div>
                
                
                {% for video in videos %}
                  <div class="mt-6 flex w-full flex-none gap-x-4 border-t border-gray-50/10 px-6 py-6">
                      <dt class="flex-none">
                      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="h-6 w-5 text-gray-400">
                          <path d="M4.5 4.5a3 3 0 0 0-3 3v9a3 3 0 0 0 3 3h8.25a3 3 0 0 0 3-3v-9a3 3 0 0 0-3-3H4.5ZM19.94 18.75l-2.69-2.69V7.94l2.69-2.69c.944-.945 2.56-.276 2.56 1.06v11.38c0 1.336-1.616 2.005-2.56 1.06Z" />
                        </svg>
                        
                        
                      </dt>
                      <dd class="text-sm/6 font-medium text-blue-400"><a href="{{video.video.url}}">{{video.mentorado}}</a></dd><p class="text-sm/6 text-white">10 - 5</p>
                  </div>
                {% endfor %}
                
                
                
                
            </div>
            </div>
    
            <!-- Invoice -->
            <div class="-mx-4 px-4 py-8 shadow-sm  sm:mx-0 sm:rounded-lg sm:px-8 sm:pb-14 lg:col-span-2 lg:row-span-2 lg:row-end-2 xl:px-16 xl:pb-20 xl:pt-16 ring-1 ring-white/20 bg-[#0b1526]">
                <h2 class="mt-4 text-2xl/9 font-bold tracking-tight text-gray-100">Tarefas do mentorado</h2>
                <hr class="border-px border-slate-800">
                
                <div class="grid grid-cols-4 gap-5 mt-4">
                   
                      <div class="col-span-3">
                        <form action="{% url 'tarefa' mentorado.id %}" method="POST">{% csrf_token %}
                          <input type="text" name="tarefa" autocomplete="email" required class="block w-full rounded-md bg-white/5 px-3 py-1.5 text-base text-white outline outline-1 -outline-offset-1 outline-white/10 placeholder:text-gray-500 focus:outline focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-500 sm:text-sm/6" placeholder="Tarefas...">
                      </div>
                      <div>
                          <button type="submit" class="flex w-full justify-center cursor-pointer rounded-md bg-indigo-600 px-3 py-1.5 text-sm/6 font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Entrar</button>
                      </div>
                    </form>
                </div>
                <br>
                
                {% for tarefa in tarefas %} 
                  <div class="flex items-center mb-4">
                      <input id="default-checkbox" type="checkbox" value="" class="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded-sm focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600">
                      <label for="default-checkbox" class="ms-2 text-sm font-medium text-gray-900 dark:text-gray-300">{{tarefa.tarefa}}</label>
                  </div>
                {% endfor %}
            </div>
    
            
    
            
            </div>
        </div>
        </div>
    </div>
  </main>
  

 
{% endblock 'body' %}